### PR TITLE
setup: Using Popen instead of check_output

### PR DESCRIPTION
**Pull request by david-caro**
So it's 2.6.6 compatible

### CODE REVIEW

**Comment by lukas-bednar** [comment]
Hi @david-caro , you may add py26 to .travis.yml and tox.ini in order to keep it py26 compatible.

**Comment by david-caro** [comment]
Hey @lukas-bednar :), already did, probably I should have separated it in another commit :/, on it

**Comment by david-caro** [comment]
Now, two commits :smile:

**Comment by david-caro** [comment]
I forgot about the travis file :blush:

**Pull request merged**
