### PR TITLE
Fixed match for resources with special plural names

### PR DESCRIPTION
**Pull request by david-caro**
* Major refactor of the metaclasses and function generating methods
* Track unbound methods
* Forcing required params from function definitions
* Improved handling of complex api endpoints:

    An endpoint like /api/resource1/{id1}/resource2/{id2}/another for the
    methods index will be mapped to:
        Resource1.resource2_another_index(id1, id2, <and any non-url params>)

* Improved the parameter documentation, now all of them state if they are
  required or not
* Added tests module
* Added test run to tox config
* Added requirements and test-requirements files

Change-Id: Ie3e6e0e2660761b0cb1117dfd6ada0d2449c5a41
Signed-off-by: Lukas Bednar <lbednar@redhat.com>

### CODE REVIEW

**Comment by lukas-bednar** [comment]
Man, you just rock !

**Comment by avi3tal** [comment]
Any planning of integrating this branch to mater soon?

**Comment by david-caro** [comment]
Yes, I'm waiting for some feedback, have you been able to test it?

**Comment by avi3tal** [comment]
Yes, I am working with this branch intensively on my own project and looks
like it is a great success :)
The merge is important since I am fully developed on these changes and it
blocks me from distributing my code.

Note: I'm using foreman 1.7.2 (will update to 1.7.5 to fix some major bugs
in foreman ).

It will be nice if you could merge you branch to master.

Thanks

**Comment by avi3tal** [comment]
Any progress?

**Comment by avi3tal** [comment]
Thanks for the merge!
Any plan to generate new release 0.2.3 ?

**Comment by david-caro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Yes, as soon as I have time I want to merge a couple more PRS and do de release, this week most probably.

On April 28, 2015 2:07:17 PM CEST, avi tal <notifications@github.com> wrote:
>Thanks for the merge!
>Any plan to generate new release 0.2.3 ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/david-caro/python-foreman/pull/37#issuecomment-97037848

- --
Sent from my Android device with K-9 Mail through Mykolab servers.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFLBAEBCgA1BQJVP3hwLhxEYXZpZCBDYXJvIChSZWRIYXQga2V5KSA8ZGNhcm9l
c3RAcmVkaGF0LmNvbT4ACgkQQHHH4dJiacPstgf+MeUKvE4qf3avGq8vgRXl5zlW
55xCV0SgoJEy179o4M3ELStTtjQM57QQX2IUmfy2t/VfAPBCk1hROus1tj0mt82l
gh50Mi21A245I+Qi2e3VdFu1PM24EA98DkcXk/SMUxLyMtPILBnYM8xJ29jTrV6W
ghdKUJzFny2NC41vMzdg252KiW9hW24qf8LM34LcqrGH0gJ+tYQFLwUrjduR79vp
UUs4wXS37PSrnP+Up5WvjzJQrL0ynXboo1s6AhR/sZ8IipAwANWYJfjq8HeWAP69
S3QWZwiR8aDzg9I+vdOVOzpWXf+qH51pfXDf9tm7Iu8lb8VCs5jekB1pKepHNw==
=IG1D
-----END PGP SIGNATURE-----

**Comment by avi3tal** [comment]
You are the man! :+1:

**Pull request merged**
